name: Test with Playwright and VPN

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup OpenVPN with credentials
        run: |
          echo "${{ secrets.VPN_CONFIG_BASE64 }}" | base64 --decode > vpn_config.ovpn
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > vpn_auth.txt
          sudo apt-get update
          sudo apt-get install -y openvpn
          sudo openvpn --config vpn_config.ovpn --auth-user-pass vpn_auth.txt --daemon

      - name: Run tests
        run: |
          npx playwright test