name: Test with Playwright and VPN

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenVPN
      run: |
        # Descargar el archivo .ovpn en base64
        curl -s https://github.com/hdvergara/execution-actions/actions/secrets/vpn_config \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          > vpn_config.txt.b64

        # Decodificar el archivo
        base64 -d vpn_config.txt.b64 > vpn_config.ovpn

        # Iniciar OpenVPN (ajusta la contraseña)
        sudo openvpn --config vpn_config.ovpn --auth-user-pass /dev/stdin << EOF
        ${{ secrets.VPN_PASSWORD }}
        EOF
    - name: Install dependencies
      run: npm install
    - name: Run Playwright tests
      run: npx playwright test